version: '3.1'

services:

  db:
    container_name: database
    image: postgres
    restart: always
    ports:
    - 5432:5432
  #  network_mode: "host"
    env_file:
      - ".env"

  tgbot:
    container_name: bot_birzha
    build:
      context: .
    command: python main.py
    restart: always
    env_file:
      - ".env"
    depends_on:
      - db


